"""add statistics models

Revision ID: 75f484f601aa
Revises: 5cf13089c9a8
Create Date: 2026-09-03 14:13:53.694221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f484f601aa'
down_revision: Union[str, Sequence[str], None] = '5cf13089c9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('application_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['stats.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['stats.user_id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_who_viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['stats.user_id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_who_viewed')
    op.drop_table('profile_viewed')
    op.drop_table('application_history')
    op.drop_table('stats')
    # ### end Alembic commands ###
