"""delete table

Revision ID: 507a85b11fba
Revises: 75f484f601aa
Create Date: 2026-09-03 14:52:43.797231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507a85b11fba'
down_revision: Union[str, Sequence[str], None] = '75f484f601aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_who_viewed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_who_viewed',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['stats.user_id'], name=op.f('user_who_viewed_user_id_fkey')),
    sa.ForeignKeyConstraint(['user_profile_id'], ['users.id'], name=op.f('user_who_viewed_user_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_who_viewed_pkey'))
    )
    # ### end Alembic commands ###
