"""Change something on models for saerch user auto

Revision ID: 34ae9a498cec
Revises: 507a85b11fba
Create Date: 2026-09-22 13:50:42.757132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ae9a498cec'
down_revision: Union[str, Sequence[str], None] = '507a85b11fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_full_name_prefix', 'users', ['full_name'], unique=False, postgresql_ops={'full_name': 'varchar_pattern_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_full_name_prefix', table_name='users', postgresql_ops={'full_name': 'varchar_pattern_ops'})
    # ### end Alembic commands ###
