"""import User and Profile

Revision ID: 5cf13089c9a8
Revises: a22051f5cb27
Create Date: 2026-08-28 15:03:40.208259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf13089c9a8'
down_revision: Union[str, Sequence[str], None] = 'a22051f5cb27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=555), nullable=True),
    sa.Column('about_me', sa.String(length=555), nullable=True),
    sa.Column('facebook_url', sa.String(length=555), nullable=True),
    sa.Column('instagram_url', sa.String(length=555), nullable=True),
    sa.Column('linkedin', sa.String(length=555), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
